# Generated by Django 3.0.5 on 2021-06-05 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simpleApi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='gender',
        ),
    ]
